use_frameworks!

target 'ReaderSDKSample' do
  pod 'Ably', '~> 1.1.3'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireNetworkActivityLogger', '~> 2.3'
  pod 'AppCenter'
  pod 'AppCenter/Distribute'
  pod 'Blueprints'
  pod 'BubbleTransition', '~> 3.0.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'CurrencyText'
  pod 'Fabric', '~> 1.9.0'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'GMStepper'
  pod 'Heap'
  pod 'Hero'
  pod 'IBAnimatable'
  pod 'JMMaskTextField-Swift'
  pod 'lottie-ios'
  pod 'M13Checkbox'
  pod 'ModelMapper'
  pod 'SDWebImage'
  pod 'Smooch'
  #pod 'Soundable', '~> 1.0'
  pod 'SwiftyTimer'
  pod 'SwiftyUserDefaults', '4.0.0-beta.2'
  pod 'Parse'
  #pod 'Pastel'
  #pod 'Peek'
end
